# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# set the default branch
# default: empty, the default branch on GitHub
branch: main

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every day"

# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
assignees:
    - "{{ cookiecutter.github_username }}"

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
label_prs: "fix(pyup): "

# set a global prefix for PRs
# default: empty
pr_prefix: "fix(pyup): "

# allow to close stale PRs
# default: True
close_prs: False

requirements:
    - "requirements.txt"
    - "docs/requirements.txt"
